all: build run

build:
	javac -cp ".:./jar/xstream-1.4.6.jar:./jar/xmlpull-1.1.3.1.jar:jar/xpp3_min-1.1.4c.jar" Main.java contact/Contact.java contact/ContactImpl.java

run:
	java -cp ".:./jar/xstream-1.4.6.jar:./jar/xmlpull-1.1.3.1.jar:jar/xpp3_min-1.1.4c.jar" Main